@address = http://localhost:1339

POST {{address}}/vip/notifications
Content-Type: application/json

{
  "problem": "http://localhost:1337/employes/83989383/problems/8398398",
  "description": "My stuff is broken again! Help!"
}


### 
GET http://localhost:1337/vipapi/problems/71bcce70-52c3-4287-b171-d1744c84dd85

###
GET {{address}}/vip/notifications/71bcce70-52c3-4287-b171-d1744c84dd85